import styles from "@/styles/Home.module.css";
import { Alert, Card, CardContent, Snackbar } from "@mui/material";
import axios from "axios";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [open, setOpen] = useState(false);

  const handleClose = (
    event?: React.SyntheticEvent | Event,
    reason?: string
  ) => {
    if (reason === "clickaway") {
      return;
    }

    setOpen(false);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Card>
          <CardContent>
            <input
              type="file"
              onChange={(e) => {
                const selectedFile = e.target?.files?.[0] as File;

                axios
                  .put(
                    `https://cloudflare.usman-bestdev.workers.dev/${selectedFile?.name}`,
                    null,
                    {
                      headers: {
                        "Access-Control-Allow-Origin": "*",
                        "Access-Control-Allow-Headers": "*",
                        "Access-Control-Allow-Credentials": "true",
                      },
                    }
                  )
                  .then((response) => {
                    var r = new FileReader();
                    r.readAsArrayBuffer(selectedFile);

                    r.onload = function () {
                      axios
                        .put(response.data, r.result, {
                          headers: {
                            "Content-Type": selectedFile.type,
                            "Access-Control-Allow-Origin": "*",
                            "Access-Control-Allow-Headers": "*",
                            "Access-Control-Allow-Credentials": "true",
                          },
                        })
                        .then((response) => {
                          setOpen(true);
                        })
                        .catch((err) => {
                          console.log(
                            "🚀 ~ file: index.tsx:43 ~ .then ~ err:",
                            err
                          );
                        });
                    };
                  })
                  .catch((err) => {
                    console.log(err);
                  });
              }}
            />
          </CardContent>
        </Card>
        <Snackbar open={open} autoHideDuration={6000} onClose={handleClose}>
          <Alert
            onClose={handleClose}
            severity="success"
            sx={{ width: "100%" }}
          >
            File uploaded successfully!
          </Alert>
        </Snackbar>
      </main>
    </>
  );
}
