import styles from "@/styles/Home.module.css";
import { Alert, Card, CardContent, Snackbar } from "@mui/material";
import axios from "axios";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useState } from "react";
import uploadFile from "../../common/splitfile";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [open, setOpen] = useState(false);

  const handleClose = (
    event?: React.SyntheticEvent | Event,
    reason?: string
  ) => {
    if (reason === "clickaway") {
      return;
    }

    setOpen(false);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Card>
          <CardContent>
            <input
              type="file"
              onChange={(e) => {
                const selectedFile = e.target?.files?.[0] as File;
                uploadFile(selectedFile);
              }}
            />
          </CardContent>
        </Card>
        <Snackbar open={open} autoHideDuration={6000} onClose={handleClose}>
          <Alert
            onClose={handleClose}
            severity="success"
            sx={{ width: "100%" }}
          >
            File uploaded successfully!
          </Alert>
        </Snackbar>
      </main>
    </>
  );
}
