import styles from "@/styles/Home.module.css";
import { Card, CardContent } from "@mui/material";
import axios from "axios";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Card>
          <CardContent>
            <input
              type="file"
              onChange={(e) => {
                const selectedFile = e.target?.files?.[0] as File;

                axios
                  .put(
                    `https://cloudflare.usman-bestdev.workers.dev/${selectedFile?.name}`,
                    null,
                    {
                      headers: {
                        "Access-Control-Allow-Origin": "*",
                        "Access-Control-Allow-Headers": "*",
                        "Access-Control-Allow-Credentials": "true",
                      },
                    }
                  )
                  .then((response) => {
                    var r = new FileReader();
                    r.readAsArrayBuffer(selectedFile);

                    r.onload = function () {
                      axios
                        .put(response.data, r.result, {
                          headers: {
                            "Content-Type": selectedFile.type,
                            "Access-Control-Allow-Origin": "*",
                            "Access-Control-Allow-Headers": "*",
                            "Access-Control-Allow-Credentials": "true",
                          },
                        })
                        .then((response) => {
                          console.log(
                            "🚀 ~ file: index.tsx:42 ~ .then ~ response:",
                            response
                          );
                        })
                        .catch((err) => {
                          console.log(
                            "🚀 ~ file: index.tsx:43 ~ .then ~ err:",
                            err
                          );
                        });
                    };
                    // axios
                    //   .put(response.data, selectedFile, {
                    //     headers: {
                    //       "Content-Type": selectedFile.type,
                    //     },
                    //   })
                    //   .then((response) => {
                    //     console.log(
                    //       "🚀 ~ file: index.tsx:42 ~ .then ~ response:",
                    //       response
                    //     );
                    //   })
                    //   .catch((err) => {
                    //     console.log(
                    //       "🚀 ~ file: index.tsx:43 ~ .then ~ err:",
                    //       err
                    //     );
                    //   });
                  })
                  .catch((err) => {
                    console.log(err);
                  });
              }}
            />
          </CardContent>
        </Card>
      </main>
    </>
  );
}
